'use client';
import { useState, useEffect } from 'react';
import { useAuth } from './components/AuthContext';
import { useRouter } from 'next/navigation';
import UserPreferences from './components/UserPreferences';
import NewsFeed from './components/NewsFeed';

interface UserPreferencesData {
  userId: string | null;
  categories: string[];
  createdAt: string;
  updatedAt: string;
  llmContext?: {
    preferenceString: string;
    categoryCount: number;
    prompt: string;
  };
}

type ViewType = 'landing' | 'preferences' | 'main';

export default function Home() {
  const { user, loading } = useAuth();
  const router = useRouter();
  const [currentView, setCurrentView] = useState<ViewType>('landing');
  const [userPreferences, setUserPreferences] = useState<UserPreferencesData | null>(null);
  const [checkingPreferences, setCheckingPreferences] = useState(true);

  // Check user preferences when authenticated
  useEffect(() => {
    const checkUserPreferences = async () => {
      if (!user) {
        setCheckingPreferences(false);
        return;
      }

      try {
        // Fetch authenticated user's preferences
        const response = await fetch('/api/preferences/auth');
        if (response.ok) {
          const data = await response.json();
          setUserPreferences(data);
          
          // If user has preferences, go to main view
          if (data.categories && data.categories.length > 0) {
            setCurrentView('main');
          } else {
            // User is logged in but has no preferences set
            setCurrentView('preferences');
          }
        } else {
          // No preferences found, show preferences page
          setCurrentView('preferences');
        }
      } catch (error) {
        console.error('Error loading preferences:', error);
        setCurrentView('preferences');
      } finally {
        setCheckingPreferences(false);
      }
    };

    if (!loading) {
      checkUserPreferences();
    }
  }, [user, loading]);

  const handleSignUpClick = (): void => {
    router.push('/signup');
  };

  const handleSignInClick = (): void => {
    router.push('/signin');
  };

  const handlePreferencesComplete = (preferences: UserPreferencesData): void => {
    setUserPreferences(preferences);
    setCurrentView('main');
  };

  // Show loading state while checking auth
  if (loading || checkingPreferences) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="text-center">
          <div className="w-12 h-12 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-gray-600">Loading...</p>
        </div>
      </div>
    );
  }

  // Landing View - Only for non-authenticated users
  if (!user && currentView === 'landing') {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-600 to-purple-700">
        <div className="text-center pt-16 pb-8 px-4">
          <h1 className="text-6xl font-bold text-white mb-6">
            InformedNow
          </h1>
          <p className="text-2xl text-blue-100 mb-4">
            Clear, Relevant, Unbiased News
          </p>
          <p className="text-lg text-blue-200 mb-8">
            Aggregated from multiple sources, summarized by AI, and personalized for you.
          </p>
          <div className="flex gap-4 justify-center">
            <button
              onClick={handleSignUpClick}
              className="px-8 py-4 bg-white text-blue-600 rounded-xl font-bold text-lg hover:bg-blue-50 transition-all shadow-xl hover:shadow-2xl hover:scale-105"
            >
              Get Started
            </button>
            <button
              onClick={handleSignInClick}
              className="px-8 py-4 bg-transparent border-2 border-white text-white rounded-xl font-bold text-lg hover:bg-white hover:text-blue-600 transition-all shadow-xl"
            >
              Sign In
            </button>
          </div>
        </div>
        <div className="py-8 px-4">
          <div className="max-w-4xl mx-auto">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
              <div className="bg-white bg-opacity-10 backdrop-blur-lg rounded-xl p-6">
                <div className="text-4xl mb-4">🎯</div>
                <h3 className="text-xl font-bold text-white mb-2">Personalized</h3>
                <p className="text-blue-100">News tailored to your interests and preferences</p>
              </div>
              <div className="bg-white bg-opacity-10 backdrop-blur-lg rounded-xl p-6">
                <div className="text-4xl mb-4">🤖</div>
                <h3 className="text-xl font-bold text-white mb-2">AI-Powered</h3>
                <p className="text-blue-100">Summaries and context generated by advanced AI</p>
              </div>
              <div className="bg-white bg-opacity-10 backdrop-blur-lg rounded-xl p-6">
                <div className="text-4xl mb-4">🌍</div>
                <h3 className="text-xl font-bold text-white mb-2">Unbiased</h3>
                <p className="text-blue-100">Multiple sources aggregated for balanced coverage</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Preferences View - For authenticated users without preferences
  if (user && currentView === 'preferences') {
    return <UserPreferences onComplete={handlePreferencesComplete} />;
  }

  // Main News Feed View - For authenticated users with preferences
  if (user && currentView === 'main') {
    return (
      <div className="min-h-screen bg-gray-50">
        <div className="bg-white border-b shadow-sm">
          <div className="max-w-7xl mx-auto px-4 py-6 flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Your News Feed</h1>
              <p className="text-sm text-gray-600 mt-1">Personalized articles based on your interests</p>
            </div>
            <button
              onClick={() => setCurrentView('preferences')}
              className="px-5 py-2.5 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium shadow-sm"
            >
              ⚙️ Edit Preferences
            </button>
          </div>
        </div>
        
        <main className="py-8">
          <NewsFeed />
        </main>
      </div>
    );
  }

  return null;
}